# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

    
trigger:
- main

pool:
   vmImage: ubuntu-latest

stages:
- stage: 'Model_CI'
  displayName: 'Model CI'
  jobs:
  - job: "Model_CI_Pipeline"
    displayName: "Model CI Pipeline"
    timeoutInMinutes: 0
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pip install azureml-sdk
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pip install pandas
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'amlpipelinedeploy'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          python -m IngestDataPipeline.yml
      displayName: 'Publish Azure Machine Learning Pipeline'
    
